CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ClassRooms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Section" text NOT NULL,
    CONSTRAINT "PK_ClassRooms" PRIMARY KEY ("Id")
);

CREATE TABLE "Subjects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ClassRoomId" integer NOT NULL,
    CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subjects_ClassRooms_ClassRoomId" FOREIGN KEY ("ClassRoomId") REFERENCES "ClassRooms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ClassRoomId" integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_ClassRooms_ClassRoomId" FOREIGN KEY ("ClassRoomId") REFERENCES "ClassRooms" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Assignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "MaxMarks" numeric NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TeacherId" integer NOT NULL,
    "ClassRoomId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Assignments_ClassRooms_ClassRoomId" FOREIGN KEY ("ClassRoomId") REFERENCES "ClassRooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Assignments_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Assignments_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SubjectTeachers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeacherId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    CONSTRAINT "PK_SubjectTeachers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubjectTeachers_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubjectTeachers_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Submissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnswerContent" text NOT NULL,
    "FilePath" text,
    "Status" integer NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "ObtainedMarks" numeric,
    "TeacherFeedback" text,
    "ReviewedByTeacherId" integer,
    "ReviewedAt" timestamp with time zone,
    "AssignmentId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    CONSTRAINT "PK_Submissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Submissions_Assignments_AssignmentId" FOREIGN KEY ("AssignmentId") REFERENCES "Assignments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Submissions_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Assignments_ClassRoomId" ON "Assignments" ("ClassRoomId");

CREATE INDEX "IX_Assignments_SubjectId" ON "Assignments" ("SubjectId");

CREATE INDEX "IX_Assignments_TeacherId" ON "Assignments" ("TeacherId");

CREATE INDEX "IX_Subjects_ClassRoomId" ON "Subjects" ("ClassRoomId");

CREATE INDEX "IX_SubjectTeachers_SubjectId" ON "SubjectTeachers" ("SubjectId");

CREATE INDEX "IX_SubjectTeachers_TeacherId" ON "SubjectTeachers" ("TeacherId");

CREATE INDEX "IX_Submissions_AssignmentId" ON "Submissions" ("AssignmentId");

CREATE INDEX "IX_Submissions_StudentId" ON "Submissions" ("StudentId");

CREATE INDEX "IX_Users_ClassRoomId" ON "Users" ("ClassRoomId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813195324_InitialCreate', '10.0.10');

COMMIT;

